### ISSUE TITLE
Demo isn't working

### ISSUE THREAD

**Issue by ghost** [corneliucirlan/mdstrap#1]
Hey there, 

FYI: It seems the demo page you set up isn't working. I'm using Chrome 51.0.2704.103 (64-bit). I did get it working locally via the download.

I'm interested in a left side and right side version of this. I am also very interested in a multi-level version like the one Foundation released in v6. [Seen Here](http://foundation.zurb.com/sites/docs/v/5.5.3/components/offcanvas.html#off-canvas-multilevel-menu)

Thanks!

**Comment by corneliucirlan** [comment]
Hey dflatjason,

Sorry for the long overdue response, I stopped working on this for a while. By now it should be working the demo.

I had planned to develop this further to include left/right side menu. I was working on something else and it totally slipped my mind.

I think I'll implement the features you requested in the next few days, if you're still interested

Corneliu
