### ISSUE TITLE
The demo doesn't work in Chrome/Safari (OSX)

### ISSUE THREAD

**Issue by 4pixels** [corneliucirlan/mdstrap#2]
Hi Corneliu

I was just installing the plugin but then noticed the demo from github and this page doesn't work so have stopped. Are you seeing the same issue?
http://www.jqueryscript.net/demo/jQuery-Off-canvas-Menu-Plugin-For-Bootstrap-4-mdstrap/

**Comment by corneliucirlan** [comment]
It's not because of the OS. I'm running Windows and still not working. The jQuery you're loading is async and by the time the code runs, it has no idea what jQuery is.

Try removing the async atribute, it will work then.

**Comment by 4pixels** [comment]
Thanks Corneliu
I'll install locally and see if it works OK.
Andy

**Comment by corneliucirlan** [comment]
You're welcome Andy.
