### ISSUE TITLE
Updating to jQuery 3.2.1

### ISSUE THREAD

**Issue by ajbiz** [corneliucirlan/mdstrap#6]
Hello Corneliu,

The plugin doesn't work with the latest version of jQuery (3.2.1), but is compatible with jQuery from 2 major versions ago (1.10.2). This is because of the use of the attribute `selector` has been deprecated.

Per this article, I updated the code to take in the name of the selector for now. 
https://api.jquery.com/selector/

Looks like all you need to do to be up to date with the latest jQuery is to make these modifications:

**lines 16-19**
`$.fn.mdStrap = function(selector, options)
    {
        // Declare function variables
        var $menu = $(selector);`

and 

**lines 44-45**
```
if ($('ul' + selector).length !== 0) initialize(settings, internal, $menu, $menuParent);
else console.error("Menu '" + selector + "' not available.");
```

I also noticed that `.md-overlay` was covering the entire screen and preventing clicking on menu items. I fixed this by setting this in my own css:

```
.navbar.navbar-toggleable-md.mds-active.bg-primary .navbar-nav {
    z-index:999;
}

.mds-overlay {
    z-index:900;
}
```

Thanks!
Aprille

**Comment by corneliucirlan** [comment]
Hi @ajbiz,

Thank you for the fixes. I added them and it seems to be working okay.

- Corneliu
